apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: ghcr.io/basher83/tailnet-microservices/anthropic-oauth-proxy
    newTag: main
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - admin-service.yaml
  - ingress.yaml
